"""Canonical application data models."""

from app.models.citations import (
    AnswerCitationSegment,
    Citation,
    CitationLocator,
    CsvCitationLocator,
    DatabaseCitationLocator,
    PdfCitationLocator,
    WebsiteCitationLocator,
)
from app.models.database import (
    DatabaseColumn,
    DatabaseDialect,
    DatabaseIsolationMode,
    DatabaseSourceRequest,
    DatabaseSourceResult,
    DatabaseTablePolicy,
    DatabaseTableSchema,
    GeneratedSql,
    ValidatedSql,
)
from app.models.documents import Evidence, NormalizedDocument, RawDocument
from app.models.graph import (
    BatchGraphExtraction,
    DocumentGraphExtraction,
    EntityType,
    ExtractedEntity,
    ExtractedRelationship,
    GraphEntity,
    GraphGenerationMetadata,
    GraphIndexRequest,
    GraphIndexResult,
    GraphPathSupport,
    GraphRelationship,
    GraphSnapshot,
    GraphSupport,
    RelationshipType,
)
from app.models.health import HealthResponse
from app.models.ingestion import (
    CrawlFailure,
    CrawlManifest,
    CsvColumnPreview,
    CsvColumnType,
    CsvIngestionResult,
    CsvPreviewResult,
    PdfIngestionResult,
    WebsiteIngestionRequest,
    WebsiteIngestionResult,
)
from app.models.query import (
    FusionContribution,
    FusionStrategy,
    QueryRequest,
    QueryResponse,
    RetrievalMode,
    SourceIndexResult,
)
from app.models.routing import RoutingIntent, RoutingKind, RoutingRuleMatch, RoutingTrace
from app.models.sources import Source, SourceConfig, SourceStatus, SourceType, SourceUpdate

__all__ = [
    "AnswerCitationSegment",
    "BatchGraphExtraction",
    "Citation",
    "CitationLocator",
    "CrawlFailure",
    "CrawlManifest",
    "CsvCitationLocator",
    "CsvColumnPreview",
    "CsvColumnType",
    "CsvIngestionResult",
    "CsvPreviewResult",
    "DatabaseCitationLocator",
    "DatabaseColumn",
    "DatabaseDialect",
    "DatabaseIsolationMode",
    "DatabaseSourceRequest",
    "DatabaseSourceResult",
    "DatabaseTablePolicy",
    "DatabaseTableSchema",
    "DocumentGraphExtraction",
    "EntityType",
    "Evidence",
    "ExtractedEntity",
    "ExtractedRelationship",
    "FusionContribution",
    "FusionStrategy",
    "GeneratedSql",
    "GraphEntity",
    "GraphGenerationMetadata",
    "GraphIndexRequest",
    "GraphIndexResult",
    "GraphPathSupport",
    "GraphRelationship",
    "GraphSnapshot",
    "GraphSupport",
    "HealthResponse",
    "NormalizedDocument",
    "PdfCitationLocator",
    "PdfIngestionResult",
    "QueryRequest",
    "QueryResponse",
    "RawDocument",
    "RelationshipType",
    "RetrievalMode",
    "RoutingIntent",
    "RoutingKind",
    "RoutingRuleMatch",
    "RoutingTrace",
    "Source",
    "SourceConfig",
    "SourceIndexResult",
    "SourceStatus",
    "SourceType",
    "SourceUpdate",
    "ValidatedSql",
    "WebsiteCitationLocator",
    "WebsiteIngestionRequest",
    "WebsiteIngestionResult",
]
